version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      args:
        LOCAL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - enrollment
    restart: on-failure
    environment:
      DISABLE_RATE_LIMITER: ${DISABLE_RATE_LIMITER:-false}
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_NAME: "postgres"

  db:
    container_name: db
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge
